# Generated by Django 4.2.5 on 2023-12-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_group_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_list', models.JSONField(verbose_name='Approved students list')),
                ('group', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='classroom.group')),
            ],
        ),
    ]
