# Generated by Django 4.2.5 on 2023-12-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_approvedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlist',
            name='missing_list',
            field=models.JSONField(default=None, verbose_name='Missing students list'),
        ),
        migrations.AlterField(
            model_name='approvedlist',
            name='approved_list',
            field=models.JSONField(default=None, verbose_name='Approved students list'),
        ),
    ]
