# Generated by Django 4.2.5 on 2023-12-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_approvedlist_not_missing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlist',
            name='not_missing_list',
            field=models.JSONField(default=None, verbose_name='Not missing students list'),
        ),
    ]
