# Generated by Django 4.2.5 on 2023-12-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_approvedlist_not_missing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlist',
            name='missing_list',
            field=models.JSONField(default=None, verbose_name='List of missing students'),
        ),
        migrations.AlterField(
            model_name='approvedlist',
            name='approved_list',
            field=models.JSONField(default=None, verbose_name='List of approved students'),
        ),
        migrations.AlterField(
            model_name='approvedlist',
            name='not_missing_list',
            field=models.JSONField(default=None, verbose_name='List of not missing students'),
        ),
    ]
