# Generated by Django 4.2.5 on 2023-12-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_approvedlist_unknown_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovedList',
            new_name='Lists',
        ),
    ]
