# Generated by Django 4.2.5 on 2024-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_rename_approvedlist_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do grupo'),
        ),
    ]
