# Generated by Django 4.1.13 on 2024-02-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='classroom.group'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classroom.group')),
            ],
        ),
    ]
