# Generated by Django 4.1.13 on 2024-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_alter_lists_group_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='associated_form_id',
            field=models.IntegerField(default=0, verbose_name='ID do formulário de inscrição associado'),
        ),
    ]
