# Generated by Django 4.1.13 on 2024-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_group_associated_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='associated_form_id',
            field=models.CharField(default=None, max_length=2000, verbose_name='ID do formulário de inscrição associado'),
        ),
    ]
